if [ -z "$MACOSX_DEPLOYMENT_TARGET" ]; then
    export MACOSX_DEPLOYMENT_TARGET="@MACOSX_DEPLOYMENT_TARGET@"
else
    export CONDA_SYSROOT_@PLATFORM@_BACKUP_MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET}"
    export MACOSX_DEPLOYMENT_TARGET="@MACOSX_DEPLOYMENT_TARGET@"
fi

if [ -z "${CONDA_BUILD_SYSROOT}" ]; then
    export CONDA_BUILD_SYSROOT="@OSX_SDK_DIR@/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
else
    export CONDA_SYSROOT_@PLATFORM@_BACKUP_CONDA_BUILD_SYSROOT="${CONDA_BUILD_SYSROOT}"
    export CONDA_BUILD_SYSROOT="@OSX_SDK_DIR@/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
fi

if [ -z "${SDKROOT}" ]; then
    export SDKROOT="${CONDA_BUILD_SYSROOT}"
else
    export CONDA_SYSROOT_@PLATFORM@_BACKUP_SDKROOT="${SDKROOT}"
    export SDKROOT="${CONDA_BUILD_SYSROOT}"
fi

# CMAKE_OSX_SYSROOT already gets set to the SDKROOT env var if not set explicitly but just for clarity let's set it
# explicitly.
if [ -z "${CMAKE_ARGS}" ]; then
    export CMAKE_ARGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET} -DCMAKE_OSX_SYSROOT=${SDKROOT}"
else
    export CONDA_SYSROOT_@PLATFORM@_BACKUP_CMAKE_ARGS="${CMAKE_ARGS}"
    export CMAKE_ARGS="${CMAKE_ARGS} -DCMAKE_OSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET} -DCMAKE_OSX_SYSROOT=${SDKROOT}"
fi

if [ -z "${CPPFLAGS}" ]; then
    export CPPFLAGS="-mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}"
else
    export CONDA_SYSROOT_@PLATFORM@_BACKUP_CPPFLAGS="${CPPFLAGS}"
    export CPPFLAGS="${CPPFLAGS} -mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}"
fi
