{% set name = "osx-sysroot" %}
{% set version = "1" %}
{% set build = "2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ build }}
  {% if cross_target_platform == "osx-arm64" and _MACOSX_DEPLOYMENT_TARGET_[0:2]|int < 11 %}
  skip: True
  {% endif %}

outputs:
  - name: macosx_deployment_target_{{ cross_target_platform }}
    version: "{{ _MACOSX_DEPLOYMENT_TARGET_ }}"
    script: build_mdt.sh
    build:
      noarch: generic
      run_exports:
        strong:
          - __osx >={{ _MACOSX_DEPLOYMENT_TARGET_ }}
    test:
      commands:
        - "[[ ${MACOSX_DEPLOYMENT_TARGET} == '{{ _MACOSX_DEPLOYMENT_TARGET_ }}' ]]"
  - name: sdkroot_env_{{ cross_target_platform }}
    version: "{{ _MACOSX_DEPLOYMENT_TARGET_ }}"
    script: build_sdkroot_env.sh
    build:
      noarch: generic
    test:
      requires:
        - macosx_deployment_target_{{ cross_target_platform }} {{ _MACOSX_DEPLOYMENT_TARGET_ }} *_{{ build }}
      commands:
        - "[[ ${SDKROOT} == ${CONDA_BUILD_SYSROOT} ]]"
        - echo {{ MACOSX_SDK_VERSION }}

about:
  home: https://github.com/conda-forge/osx-sysroot-feedstock
  summary: metapackage to set the MACOSX_DEPLOYMENT_TARGET
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - beckermr
    - xhochy
