schema_version: 1

context:
  build_number: 7

recipe:
  name: osx-sysroot
  version: ${{ _MACOSX_DEPLOYMENT_TARGET_ }}

build:
  number: ${{ build_number }}
  skip:
    - cross_target_platform == "osx-arm64" and match(_MACOSX_DEPLOYMENT_TARGET_, "<11")

outputs:
  - package:
      name: macosx_deployment_target_${{ cross_target_platform }}
    build:
      noarch: generic
      script: build_mdt.sh
    requirements:
      run_exports:
        strong:
          - __osx >=${{ _MACOSX_DEPLOYMENT_TARGET_ }}
    tests:
      - script:
          - "[[ ${MACOSX_DEPLOYMENT_TARGET} == '${{ _MACOSX_DEPLOYMENT_TARGET_ }}' ]]"

  - package:
      name: sdkroot_env_${{ cross_target_platform }}
    build:
      noarch: generic
      script: build_sdkroot_env.sh
    tests:
      - requirements:
          run:
            # rattler-build fails with pin_subpackage here.
            - macosx_deployment_target_${{ cross_target_platform }} ==${{ _MACOSX_DEPLOYMENT_TARGET_ }} *_${{ build_number }}
        script:
          - "[[ ${SDKROOT} == ${CONDA_BUILD_SYSROOT} ]]"
          - echo ${{ MACOSX_SDK_VERSION }}

about:
  summary: metapackage to set the MACOSX_DEPLOYMENT_TARGET
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/conda-forge/osx-sysroot-feedstock

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
    - xhochy
